---
title: "Winchmore Hill & Enfield Hockey Club Men's First XI"
author: "Matt Dray"
output:
  flexdashboard::flex_dashboard:
    theme: lumen
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(dplyr)
library(ggplot2)
library(plotly)
library(emo)
source("plot_pts.R")
```

Column {data-width=200}
-------------------------------------
    
### About

#### `r emo::ji("purple_heart")` The club

[Winchmore Hill & Enfield](http://www.whehockey.com/) is a hockey club based in North London.

The men's first XI play in [East Hockey League Division 4SW](http://www.east-hockey.com/leagues2/showdata/sqlresults/resultsmen.asp?division=4SW).

#### `r emo::ji("chart_with_upwards_trend")` Plots

The plots show the cumulative number of points collected over the course of the season.

Different seasons are available in separate tabs.

Hover over the points for details on the match.

#### `r emo::ji("computer")` Tech details

* Built in R
* Packages: flexdashboard, readr, dplyr, ggplot2, plotly
* [GitHub repo](https://github.com/matt-dray/whe-hockey)
 
Column {.tabset}
-------------------------------------

### Season 2018/19

```{r}
plot_pts(file_path = "data/whe-m1-results-201819.csv") %>% 
  ggplotly()
```

### Season 2017/18

```{r}
plot_pts(file_path = "data/whe-m1-results-201718.csv") %>% 
  ggplotly()
```   
 